name: fact
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - comm=0.1.2=py38h06a4308_0
  - cudatoolkit=11.3.1=h9edb442_10
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - flit-core=3.8.0=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=8.10.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jpeg=9e=h5eee18b_1
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_core=5.3.0=py38h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.0=py38_cu113
  - tornado=6.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.4=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - attrs==22.2.0
    - avalanche-lib==0.1.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - debugpy==1.6.6
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - fastjsonschema==2.16.3
    - filelock==3.10.0
    - fqdn==1.5.1
    - gdown==4.6.4
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - grpcio==1.51.3
    - idna==3.4
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - markdown==3.4.1
    - markupsafe==2.1.2
    - mistune==2.0.5
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.8.0
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - oauthlib==3.2.2
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - pathtools==0.1.2
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.16.0
    - protobuf==4.22.1
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycparser==2.21
    - pyrsistent==0.19.3
    - pysocks==1.7.1
    - python-json-logger==2.0.7
    - pytorchcv==0.0.67
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - quadprog==0.1.11
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - send2trash==1.8.0
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - setuptools==59.5.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - timm==0.6.5
    - tinycss2==1.2.1
    - tqdm==4.65.0
    - uri-template==1.2.0
    - urllib3==1.26.15
    - wandb==0.14.0
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - zipp==3.15.0
prefix: /nfs/users/ext_arnav.chavan/miniconda3/envs/fact
